//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinarija.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kupuvac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kupuvac()
        {
            this.Narackas = new HashSet<Naracka>();
        }
    
        public int KupuvacID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string email { get; set; }
        public string adresa { get; set; }
        public Nullable<int> Godini { get; set; }
        public Nullable<int> tel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Naracka> Narackas { get; set; }
    }
}
