//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinarija.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Naracka
    {
        public int NarackaID { get; set; }
        public Nullable<int> KupuvacID { get; set; }
        public Nullable<int> VinoID { get; set; }
    
        public virtual Kupuvac Kupuvac { get; set; }
        public virtual Vino Vino { get; set; }
    }
}
