//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinarija.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProizvoditelVino
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProizvoditelVino()
        {
            this.Vinoes = new HashSet<Vino>();
        }
    
        public int ProizvoditelVinoID { get; set; }
        public string ProizvoditelVinoIme { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vino> Vinoes { get; set; }
    }
}
