//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinarija.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SostojkiVino
    {
        public int SostojkiVinoID { get; set; }
        public Nullable<int> VinoID { get; set; }
        public string Grozje { get; set; }
        public string Voda { get; set; }
        public string Seker { get; set; }
        public string Ostanato { get; set; }
    
        public virtual Vino Vino { get; set; }
    }
}
