 //------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinarija.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WineryDBEntities : DbContext
    {
        public WineryDBEntities()
            : base("name=WineryDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KolicinaVino> KolicinaVinoes { get; set; }
        public virtual DbSet<Kupuvac> Kupuvacs { get; set; }
        public virtual DbSet<Naracka> Narackas { get; set; }
        public virtual DbSet<ProizvoditelVino> ProizvoditelVinoes { get; set; }
        public virtual DbSet<SostojkiVino> SostojkiVinoes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TipVino> TipVinoes { get; set; }
        public virtual DbSet<Vino> Vinoes { get; set; }
    }
}
